load('//:buckaroo_macros.bzl', 'buckaroo_deps_from_package')

pthread = buckaroo_deps_from_package('github.com/buckaroo-pm/host-pthread')

cxx_binary(
  name = 'unittests',
  header_namespace = '',
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  deps = [
    '//:concurrentqueue',
    '//tests/common:common',
  ],
  platform_deps = [
    ('linux.*', pthread),
  ],
)
